### ISSUE TITLE
access

### ISSUE THREAD

**Issue by ghost** [browserify/discuss#3]
I went through the list of maintainers for browserify core and related repos and added everyone as an owner. This way everybody has access to all org repos and can add more people.

I would like to do the same for all the npm packages I am a maintainer on so that anybody can cut a new release on npm as well as github. Maybe we could have a file with both github and npm user names for everybody in the org? And when a new user is added, the person who added them can add their npm and github user names to that file. Where should that file live?

**Comment by gkatsev** [comment]
npm orgs might be useful for managing the npm access since all the packages can be added to the org and a team and then a user only needs to be added once to have access to everything in the team.

While the [docs](https://docs.npmjs.com/misc/orgs) for it don't say so, you can add public packages to it with something like
```sh
npm access grant read-write browserify:developers node-browserify
```

Though, npm has a bug currently where depending on permissions of users that are on the package, you might need to go through npm support for it until it gets fixed.

**Comment by ghost** [comment]
Great, I've added the packages I control to the org and added everybody as an owner so that anybody can add more people.
